### ISSUE TITLE
TypeError: Error while loading rule 'prettier/prettier': context.getPhysicalFilename is not a function

### ISSUE THREAD

**Issue by vadhe** [kodingdotninja/eslint-config-kdnj#3]
when I use "yarn lint" in terminal 
I get this error yarn run v1.22.15

```console
$ eslint --cache --fix "src/**/*.{js,jsx,ts,tsx}"

TypeError: Error while loading rule 'prettier/prettier': context.getPhysicalFilename is not a function
Occurred while linting /home/vadhe/Desktop/pallaka/ams-ui/src/App.js
    at Object.create (/home/vadhe/Desktop/pallaka/ams-ui/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js:123:40)
    at createRuleListeners (/home/vadhe/Desktop/pallaka/ams-ui/node_modules/@typescript-eslint/eslint-plugin/node_modules/eslint/lib/linter/linter.js:746:21)
    at /home/vadhe/Desktop/pallaka/ams-ui/node_modules/@typescript-eslint/eslint-plugin/node_modules/eslint/lib/linter/linter.js:916:31
    at Array.forEach (<anonymous>)
    at runRules (/home/vadhe/Desktop/pallaka/ams-ui/node_modules/@typescript-eslint/eslint-plugin/node_modules/eslint/lib/linter/linter.js:861:34)
    at Linter._verifyWithoutProcessors (/home/vadhe/Desktop/pallaka/ams-ui/node_modules/@typescript-eslint/eslint-plugin/node_modules/eslint/lib/linter/linter.js:1157:31)
    at Linter._verifyWithConfigArray (/home/vadhe/Desktop/pallaka/ams-ui/node_modules/@typescript-eslint/eslint-plugin/node_modules/eslint/lib/linter/linter.js:1255:21)
    at Linter.verify (/home/vadhe/Desktop/pallaka/ams-ui/node_modules/@typescript-eslint/eslint-plugin/node_modules/eslint/lib/linter/linter.js:1210:25)
    at Linter.verifyAndFix (/home/vadhe/Desktop/pallaka/ams-ui/node_modules/@typescript-eslint/eslint-plugin/node_modules/eslint/lib/linter/linter.js:1400:29)
    at verifyText (/home/vadhe/Desktop/pallaka/ams-ui/node_modules/@typescript-eslint/eslint-plugin/node_modules/eslint/lib/cli-engine/cli-engine.js:230:48)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Dooptroop** [comment]
> 

After updating what to v0.0.11 ? Im running into the same issue on one of my projects
